### ISSUE TITLE
.DS_Store folders in pymnt folder causes trd to fail

### ISSUE THREAD

**Issue by chiptus** [tezos-reward-distributor-organization/tezos-reward-distributor#180]
I got the following error, and fixed it by deleting .DS_Store files in my `pymnt` folder, in all subfolders: 
```
Traceback (most recent call last):
  File "src/main.py", line 205, in <module>
    main(args)
  File "src/main.py", line 137, in main
    recent = get_latest_report_file(payments_root)
  File "src/main.py", line 191, in get_latest_report_file
    key=lambda x: int(x))
  File "src/main.py", line 191, in <lambda>
    key=lambda x: int(x))
ValueError: invalid literal for int() with base 10: '.DS_Store'
```

**Comment by utdrmac** [comment]
This file is automatically created by MacOS when you open these directories in the Finder. Try not to do that, as a quick fix.
