### ISSUE TITLE
retryfailed failed - AttributeError: 'Namespace' object has no attribute 'api_base_url'

### ISSUE THREAD

**Issue by songproducer** [tezos-reward-distributor-organization/tezos-reward-distributor#253]
**Describe the bug**
retry_failed.py doesn't run
AttributeError: 'Namespace' object has no attribute 'api_base_url'

**To Reproduce**
have a failed batch.
run retry_failed.py

**Expected behavior**
work

**Screenshots**
python3 src/retry_failed.py
```
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2020-08-28 19:39:20,887 - MainThread - Tezos Reward Distributor - Retry Failed Files is Starting
2020-08-28 19:39:20,888 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "prpc",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "http://127.0.0.1:8732",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "retry_injected": false
}
2020-08-28 19:39:20,888 - MainThread - master configuration file not present.
2020-08-28 19:39:20,952 - MainThread - Loading baking configuration file /home/leo/pymnt/cfg/tz1NEKxGEHsFufk87CVZcrqWu8o22qh46GK6.yaml
Traceback (most recent call last):
  File "src/retry_failed.py", line 208, in <module>
    main(args)
  File "src/retry_failed.py", line 96, in main
    network_config, args.node_addr, api_base_url=args.api_base_url)
AttributeError: 'Namespace' object has no attribute 'api_base_url'
```
**Environment**
 - Source Code Build 
 - Chain mainnet, 
 - actual command used
python3 src/retry_failed.py
**Additional context**
have the latest code

**Comment by utdrmac** [comment]
@songproducer Can  you please check if https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/256 fixes your issue?

**Comment by songproducer** [comment]
I manually paid out. Will open again if needed. Closing.

**Comment by songproducer** [comment]
Updating the retry_failed.py worked! thanks!
