### ISSUE TITLE
NameError: name 'loggin' is not defined

### ISSUE THREAD

**Issue by songproducer** [tezos-reward-distributor-organization/tezos-reward-distributor#266]
```
Traceback (most recent call last):
  File "src/main.py", line 223, in <module>
    main(args)
  File "src/main.py", line 40, in main
    loggin.info("Anonymous statistics {} be collected. See docs/statistics.rst for more information."
NameError: name 'loggin' is not defined

```

**Comment by jdsika** [comment]
thx @adamkittelson for the fix
