### ISSUE TITLE
Exception: Lock file present. Another process is running...

### ISSUE THREAD

**Issue by k-vyn** [tezos-reward-distributor-organization/tezos-reward-distributor#278]
I keep getting when I run the script: 
```
2020-10-10 01:28:33,474 - MainThread - --------------------------------------------
Traceback (most recent call last):
  File "src/main.py", line 225, in <module>
    main(args)
  File "src/main.py", line 146, in main
    life_cycle.start(not dry_run)
  File "/Users/-/tezos-reward-distributor/src/util/process_life_cycle.py", line 20, in start
    self.lock_file.lock()
  File "/Users/-/tezos-reward-distributor/src/util/lock_file.py", line 10, in lock
    self.tryLock()
  File "/Users/-tezos-reward-distributor/src/util/lock_file.py", line 20, in tryLock
    raise Exception("Lock file present. Another process is running...")
Exception: Lock file present. Another process is running...
```
Not sure how this happened, but I have to imagine the last script didn't end neatly. How do I go about reseting this? Can't seem to find a command.

Thanks!

**Comment by dansan566** [comment]
@k-vyn We had the same issue once. Quick fix: delete the lock file in the trd folder

**Comment by jdsika** [comment]
@amzid should we add a command to delete the lock file with a warning to only do it when the application crashed?

**Comment by k-vyn** [comment]
I tried deleting the lock file, but I then get this 

```
  File "src/main.py", line 225, in <module>
    main(args)
  File "src/main.py", line 152, in main
    recent = get_latest_report_file(payments_root)
  File "src/main.py", line 210, in get_latest_report_file
    files = sorted([os.path.splitext(x)[0] for x in os.listdir(get_successful_payments_dir(payments_root))],
  File "src/main.py", line 211, in <lambda>
    key=lambda x: int(x))
ValueError: invalid literal for int() with base 10: '.DS_Store  File "src/main.py", line 225, in <module>
    main(args)
  File "src/main.py", line 152, in main
    recent = get_latest_report_file(payments_root)
  File "src/main.py", line 210, in get_latest_report_file
    files = sorted([os.path.splitext(x)[0] for x in os.listdir(get_successful_payments_dir(payments_root))],
  File "src/main.py", line 211, in <lambda>
    key=lambda x: int(x))
ValueError: invalid literal for int() with base 10: '.DS_Store
```

**Comment by k-vyn** [comment]
I also tried deleting TRD and re-cloning it, but I get the same error. Should I re-create my pymnt folder?

**Comment by jdsika** [comment]
can you please check if the latest master resolves your issue?

**Comment by jdsika** [comment]
> ayments_root)

btw. I think this is due to the fact that there is a file called ".DS_Store" which causes the error. @amzid will implement a proper file name parser to avoid the mistake and ignore additional unrelated files in the directory.

**Comment by k-vyn** [comment]
Where is the .DS_Store file? I don't see one in /pymnts, and deleting the one in trd doesn't fix the error.

@amzid, I just pulled the latest merge, and I'm still getting the same error. I get the new ```y/n``` prompt for the lock file, which is super nice. 

Traceback (most recent call last):
  File "src/main.py", line 231, in <module>
    main(args)
  File "src/main.py", line 152, in main
    recent = get_latest_report_file(payments_root)
  File "src/main.py", line 214, in get_latest_report_file
    paid_cycles.append(int(x))
ValueError: invalid literal for int() with base 10: '.DS_Store'

**Comment by k-vyn** [comment]
Actually, I was just able to run it successfully by passing a start cycle ```-C``` .

But I still can't run it without passing it a cycle, it gives me the above error.

**Comment by amzid** [comment]
Can you check using #288 ?
