### ISSUE TITLE
Payment failure with preapply operation issue

### ISSUE THREAD

**Issue by Michshelle** [tezos-reward-distributor-organization/tezos-reward-distributor#280]
**Describe the bug**
With socket running by command `./tezos-signer launch socket signer -a 127.0.0.1 -p 22000`
I was trying `python3 src/main.py -C 210 -M 3`

And keep getting below error message while paying out rewards.  
Plus, port 22000 never reponses during the payment process.

```2020-10-17 16:59:13,014 - consumer0 - batch payment attempt 1/3 for current batch failed with error
2020-10-17 18:07:46,911 - MainThread - Lock file removed!
2020-10-17 18:09:39,337 - consumer0 - Command failed, error is |Error:
  Rpc request failed:
     - meth: POST
     - uri: http://127.0.0.1:8732/chains/main/blocks/head/helpers/preapply/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Unhandled error (Failure "Unexpected data (Signature)")

Traceback (most recent call last):
  File "/Users/tezos-reward-distributor/src/pay/batch_payer.py", line 215, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/Users/tezos-reward-distributor/src/pay/batch_payer.py", line 319, in attempt_single_batch
    run_ops_parsed = parse_json_response(runops_command_response, verbose=verbose)
  File "/Users/tezos-reward-distributor/src/util/rpc_utils.py", line 48, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format
```

**Environment**
 - Source code build
 - Attached configuration
`{baking_address: tz1dhwJY5B1jKdkF7zcyu1v6EBEQjpGmAp1E, delegator_pays_ra_fee: true,
    delegator_pays_xfer_fee: true, founders_map: {}, min_delegation_amt: 500.0, owners_map: {},
    payment_address: alice, reactivate_zeroed: true, rules_map: {mindelegation: TOB},
    service_fee: 4.5, specials_map: {}, supporters_set: !!set {}}`

 - Chain mainnet

 - MacOS catalina 10.15.7

- I can see after the message `2020-10-17 18:07:46,911 - MainThread - Lock file removed!`, a key-shaped icon would show up and If I hit enter, the above error message would be generated. 

![key_icon](https://user-images.githubusercontent.com/8004456/96334801-fae6a580-10a5-11eb-83da-b927bf9953b6.jpg)

**Comment by Michshelle** [comment]
Some more info found in log:
```
2020-10-18 01:23:35,391 - consumer0 - <-- Verbose : Answer is |Enter password for encrypted key: Signature: edsigtvB8BQ6FGTxQtX7JYdLtKSBZoTiQJPWzYhLS6rihyyB8sbGPUGqCyobdKLbzz2W6YPzaBigjCYyTPqm6CsNTRgjxpd4YAP|
2020-10-18 01:23:35,391 - consumer0 - Preapplying the operations
2020-10-18 01:23:35,486 - consumer0 - Command failed, error is |Error:
  Rpc request failed:
     - meth: POST
     - uri: http://127.0.0.1:8732/chains/main/blocks/head/helpers/preapply/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Unhandled error (Failure "Unexpected data (Signature)")
```
Also if I manually transfer tezos with the signer account, it can be processed successfully. the terminal running tezos-signer would sign automatically.

**Comment by Michshelle** [comment]
Okay, I made it work.   The root cause is the messy listing of aliases to the addresses.
I alias two different names to the same PKH (the signer).  One with locater  tcp://xxx, the other is the secret key.  By properly deleting the alias linked with secret key in tezos-client folder, it would work.
