### ISSUE TITLE
reward_data_provider option behaviour

### ISSUE THREAD

**Issue by xiduis15** [tezos-reward-distributor-organization/tezos-reward-distributor#284]
**Describe the bug**
I try to work with my private RPC archive node.
But I have some problems.
When i try to launch TRD with my RPC node, i have this traceback:

2020-10-23 14:55:18,927 - producer  - RPC API Error: No delegators found
Traceback (most recent call last):
  File "/home/user/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 168, in __get_delegators_and_delgators_balances
    raise RpcRewardApiError("No delegators found")

So i take a look in rpc_reward_api.py and i make a `print(get_delegates_request)` [line 147]

**_result:_**

`user@mynode:~/tezos-reward-distributor$ python3 src/main.py --executable_dirs /home/user/.opam/for_tezos/bin/ -M 3 -Dc -P prpc`

Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information

2020-10-23 15:16:16,852 - MainThread - Tezos Reward Distributor is Starting
2020-10-23 15:16:16,852 - MainThread - TRD version 5.13 is running in interactive mode.
2020-10-23 15:16:16,853 - MainThread - Arguments Configuration = {
 "initial_cycle": null,
 "run_mode": 3,
 "release_override": 0,
 "payment_offset": 0,
 "network": "MAINNET",
 "node_addr": "http://127.0.0.1:8732",
 "reward_data_provider": "prpc",
 "node_addr_public": "",
 "reports_base": "\~/pymnt/reports",
 "config_dir": "\~/pymnt/cfg",
 "dry_run": false,
 "dry_run_no_consumers": true,
 "executable_dirs": "/home/user/.opam/for_tezos/bin/",
 "docker": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "verbose": false,
 "api_base_url": null,
 "retry_injected": false
}
2020-10-23 15:16:16,853 - MainThread - Anonymous statistics will be collected. See docs/statistics.rst for more information.
2020-10-23 15:16:16,930 - MainThread - Loading baking configuration file /home/user/pymnt/cfg/tz1xxxxxxxx.yaml
2020-10-23 15:16:17,047 - MainThread - Baking Configuration {
 "master_dict": {},
 "cfg_dict": {
  "baking_address": "tz1xxxxxxxx",
  "delegator_pays_ra_fee": false,
  "delegator_pays_xfer_fee": true,
  "founders_map": {},
  "min_delegation_amt": 0.0,
  "owners_map": {},
  "payment_address": "tatayoyo",
  "reactivate_zeroed": false,
  "rules_map": {
   "mindelegation": "TOB"
  },
  "service_fee": 1.0,
  "specials_map": {},
  "supporters_set": [],
  "__payment_address_type": null,
  "__payment_address_pkh": "tz1xxxpayment",
  "__payment_address_manager": "tz1xxxpayment",
  "__full_supporters_set": [],
  "__excluded_delegators_set_toe": [],
  "__excluded_delegators_set_tof": [],
  "__excluded_delegators_set_tob": [
   "mindelegation"
  ],
  "__destination_map": {}
 }
}
2020-10-23 15:16:17,048 - MainThread - --------------------------------------------
2020-10-23 15:16:17,048 - MainThread - BAKING ADDRESS is tz1xxxxxxxx
2020-10-23 15:16:17,048 - MainThread - PAYMENT ADDRESS is paymentaddr
2020-10-23 15:16:17,048 - MainThread - --------------------------------------------
2020-10-23 15:16:17,049 - MainThread - initial_cycle set to 0
2020-10-23 15:16:17,049 - MainThread - Producer "producer" started
2020-10-23 15:16:22,087 - producer  - Checking for pending payments : checking 283 <= 289 - (5 + 1) - 0
2020-10-23 15:16:22,088 - producer  - Payment cycle is 283
###DEBUG #####
##print(get_delegates_request) 
**https://mainnet-tezos.giganode.io/chains/main/blocks/1134592/context/delegates/tz1xxxxxxxx**
2020-10-23 15:16:23,292 - producer  - RPC API Error: No delegators found
Traceback (most recent call last):
  File "/home/user/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 168, in __get_delegators_and_delgators_balances
    raise RpcRewardApiError("No delegators found")
rpc.rpc_reward_api.RpcRewardApiError: No delegators found
2020-10-23 15:16:23,646 - producer  - Total rewards before processing is 1,250,000 mutez.
2020-10-23 15:16:23,646 - producer  - Total rewards after  processing is 1,250,000 mutez.
2020-10-23 15:16:23,647 - producer  - Total payment amount is 0. Nothing to pay!
2020-10-23 15:16:33,657 - producer  - Run mode ONETIME satisfied. Terminating ...
2020-10-23 15:16:33,657 - producer  - Producer returning ...
2020-10-23 15:16:37,071 - MainThread - Interrupted.
2020-10-23 15:16:37,072 - MainThread - --------------------------------------------------------
2020-10-23 15:16:37,072 - MainThread - Sensitive operations are in progress!
2020-10-23 15:16:37,072 - MainThread - Please wait while the application is being shut down!
2020-10-23 15:16:37,072 - MainThread - --------------------------------------------------------

**Expected behavior & Question**

- get_delegates_request have to set with localhost and not with https://mainnet-tezos.giganode.io

- In the url we can see block id is 1134592. But this block is in cycle 276. Is this normal that it makes its request @block 276 even if the payment cycle is 283 ?

**Environment**
Ubuntu 18.04.5 LTS fresh install
Opam tezos install
Chain mainnet
RPC node : mainnet-tezos.giganode
actual command used
user@mynode:~/tezos-reward-distributor$ python3 src/main.py --executable_dirs /home/user/.opam/for_tezos/bin/ -M 3 -Dc -P prpc

**Comment by amzid** [comment]
In order to use your local node, you need to set the provider flag to `-P rpc` and not  `-P prpc`. Otherwise, the default public rpc node will be used.

If the payment cycle is 283, the snapshot block is in cycle 276. The snapshot block is the relevant block for calculating the staking balances of each delegator.

**Comment by xiduis15** [comment]
Thx ! it's okay for me.
