### ISSUE TITLE
Payouts fail with public nodes since the Delphi upgrade

### ISSUE THREAD

**Issue by amani1104** [tezos-reward-distributor-organization/tezos-reward-distributor#304]
**Describe the bug**
Since the Delphi upgrade on Nov 12, payouts fail when using a non-standard public node. Payouts over GigaNode still work properly and do not fail. 

The error starts almost immediately after starting up TRD and the output log is the following:

```
2020-11-13 16:48:39,659 - MainThread - --------------------------------------------
2020-11-13 16:48:39,659 - MainThread - BAKING ADDRESS is tz1xxx
2020-11-13 16:48:39,659 - MainThread - PAYMENT ADDRESS is payouts
2020-11-13 16:48:39,659 - MainThread - --------------------------------------------
2020-11-13 16:48:39,660 - MainThread - Producer "producer" started
2020-11-13 16:48:39,663 - MainThread - Consumer "consumer0" created
2020-11-13 16:48:40,665 - MainThread - Application start completed
2020-11-13 16:48:40,665 - MainThread - --------------------------------------------
2020-11-13 16:48:44,683 - producer  - Checking for pending payments : checking 290 <= 296 - (5 + 1) - 0
2020-11-13 16:48:44,683 - producer  - Payment cycle is 290
--- Logging error ---
Traceback (most recent call last):
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marc/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/marc/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='teznode.letzbake.com', port=443): Read timed out. (read timeout=5) 
```
The last block is repeated after that with the same content. 

**To Reproduce**
1. start TRD with the following command: 
`python3 src/main.py -V -E /usr/local/bin -M 3 -Ap https://teznode.letzbake.com -C 290 -D`
3. See error

**Expected behavior**
Payouts by using public nodes other than the pre-configured services should not fail. 

**Environment**
 - Source Code Build - v7.0
 - mainnet
 - Ubuntu 20.04 LTS

**Comment by amani1104** [comment]
Found the error. It was an issue with the load balancer.
