### ISSUE TITLE
NameError: name 'total_amount' is not defined

### ISSUE THREAD

**Issue by goodpen** [tezos-reward-distributor-organization/tezos-reward-distributor#308]
2020-11-15 12:26:12,762 - MainThread - --------------------------------------------
2020-11-15 12:26:12,762 - MainThread - [Plugins] No plugins enabled
2020-11-15 12:26:12,763 - MainThread - Producer "producer" started
2020-11-15 12:26:12,764 - MainThread - Consumer "consumer0" created
2020-11-15 12:26:13,766 - MainThread - Application start completed
2020-11-15 12:26:13,766 - MainThread - --------------------------------------------
2020-11-15 12:26:17,931 - producer  - Checking for pending payments : checking 291 <= 297 - (5 + 1) - 0
2020-11-15 12:26:17,931 - producer  - Payment cycle is 291
2020-11-15 12:26:21,027 - producer  - Total rewards before processing is 609,287,638 mutez.
2020-11-15 12:26:21,031 - producer  - Total rewards after processing is 596,125,989 mutez.
2020-11-15 12:26:21,031 - producer  - Total amount to pay is 596,125,984 mutez
2020-11-15 12:26:21,031 - producer  - Difference between total rewards and total payment amount is 5 mutez. This is due to floating point arithmetic. (max allowed diff is 10)
2020-11-15 12:26:22,033 - consumer0 - Starting payments for cycle 291
2020-11-15 12:26:22,033 - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/ubuntu/tezos-reward-distributor/src/pay/payment_consumer.py", line 86, in run
    payment_items = phaseMerge.calculate(payment_items)
  File "/home/ubuntu/tezos-reward-distributor/src/calc/calculate_phaseMerge.py", line 52, in calculate
    return reward_data6, total_amount
NameError: name 'total_amount' is not defined
2020-11-15 12:26:26,070 - producer  - Calculation report is created at '/home/ubuntu/pymnt/reports/tzxxxxxxx/calculations/291.csv'
2020-11-15 12:26:26,070 - producer  - Reward creation is done for cycle 291, created 463 rewards.
2020-11-15 12:26:36,081 - producer  - Run mode ONETIME satisfied. Terminating ...
2020-11-15 12:26:36,081 - producer  - Producer returning ...
2020-11-15 12:26:36,081 - consumer0 - Exit signal received. Terminating...
2020-11-15 12:26:36,082 - consumer0 - Consumer returning ...
2020-11-15 12:26:43,793 - MainThread - Interrupted.
2020-11-15 12:26:43,793 - MainThread - --------------------------------------------------------
2020-11-15 12:26:43,793 - MainThread - Sensitive operations are in progress!
2020-11-15 12:26:43,793 - MainThread - Please wait while the application is being shut down!
2020-11-15 12:26:43,793 - MainThread - ----------
**To Reproduce**
 python3 src/main.py  -P prpc --reward_data_provider tzstats     -C291 -M3
node version 7.5
TDR last update

**Comment by dansan566** [comment]
Same with `python3 src/main.py -C 291 -P tzkt -M 3 -O 10 -V -D`
