### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by k-vyn** [tezos-reward-distributor-organization/tezos-reward-distributor#311]
```Traceback (most recent call last):
  File "/~/tezos-reward-distributor/src/main.py", line 7, in <module>
    from launch_common import print_banner, parse_arguments
  File "/~/tezos-reward-distributor/src/launch_common.py", line 2, in <module>
    from NetworkConfiguration import default_network_config_map
  File "/~/tezos-reward-distributor/src/NetworkConfiguration.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Hi, 

I started to get this bug whenever I run the main script `python3 src/main.py -M 3`.

**Comment by utdrmac** [comment]
@k-vyn Did you follow the install instructions?

`pip3 install -r requirements.txt`

**Comment by k-vyn** [comment]
@utdrmac Ah perfect! That worked. 🙌
