### ISSUE TITLE
not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by gaia** [tezos-reward-distributor-organization/tezos-reward-distributor#354]
**Describe the bug**
Did a git pull today and

```
2021-01-11 11:56:19,497 - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/payment_consumer.py", line 109, in run
    batch_payer.pay(payment_items, dry_run=self.dry_run)
ValueError: not enough values to unpack (expected 4, got 3)
```
for a `main.py -M 3 -P tzkt -Dp -D -C 310`

worked fine with the above cmd before today's `git pull` (I usually git pull on every payout)

**Comment by SemElVik** [comment]
same

_python3 src/main.py -C 316 -D -P tzkt -M 3 -R -5_

```
2021-01-14 12:36:55,220 - consumer0 - [Plugins] Not sending notification; no plugins enabled
2021-01-14 12:36:55,220 - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/alex/tezos-reward-distributor/src/pay/payment_consumer.py", line 109, in run
    batch_payer.pay(payment_items, dry_run=self.dry_run)
ValueError: not enough values to unpack (expected 4, got 3)

```
~/tezos-reward-distributor$ `git log --stat`
commit `6a5ba1ca6bf63c5211796c1b7b2eaecd215be6ae`
