### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by PolosatiiPsih** [tezos-reward-distributor-organization/tezos-reward-distributor#380]
**Describe the bug**
Linux MInt 20 Ulyana.
Ledger was used previously.
Three steps were done, key was imported to signer.
Signer was run in separate window as http service.

Following error occurs:

2021-02-16 19:01:10,907 - MainThread - --------------------------------------------
2021-02-16 19:01:10,908 - MainThread - BAKING ADDRESS is tz1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-02-16 19:01:10,908 - MainThread - PAYMENT ADDRESS is tz1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-02-16 19:01:10,908 - MainThread - --------------------------------------------
2021-02-16 19:01:10,914 - MainThread - [Plugins] No plugins enabled; Check the documentation if you believe this to be incorrect
2021-02-16 19:01:10,915 - MainThread - Producer "producer" started
2021-02-16 19:01:10,916 - MainThread - Consumer "consumer0" created
2021-02-16 19:01:10,917 - producer  - No failed payment files found under directory '/user/pymnt/reports/tz1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/payments/failed'
2021-02-16 19:01:10,918 - producer_retry_fail - Retry Fail thread "producer_retry_fail" started
2021-02-16 19:01:11,919 - MainThread - Application start completed
2021-02-16 19:01:11,920 - MainThread - --------------------------------------------
2021-02-16 19:01:16,298 - producer  - Unable to determine local node's bootstrap status. Continuing...
2021-02-16 19:01:16,533 - producer  - Checking for pending payments : checking 322 <= 328 - (5 + 1) - 0
2021-02-16 19:01:16,534 - producer  - Payment cycle is 322
2021-02-16 19:01:16,536 - producer  - Using actual rewards for payouts calculations
2021-02-16 19:01:24,892 - producer  - Total rewards before processing is 19,583,333 mutez.
2021-02-16 19:01:24,897 - producer  - Total rewards after processing is 19,583,333 mutez.
2021-02-16 19:01:24,898 - producer  - Total amount to pay is 19,583,332 mutez
2021-02-16 19:01:24,898 - producer  - Difference between total rewards and total payment amount is 1 mutez. This is due to floating point arithmetic. (max allowed diff is 10)
2021-02-16 19:01:25,900 - consumer0 - Starting payments for cycle 322
2021-02-16 19:01:25,906 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegate
2021-02-16 19:01:25,907 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2021-02-16 19:01:25,907 - consumer0 - Payment amount cutoff is 0.000001 XTZ
2021-02-16 19:01:25,908 - consumer0 - 102 payment items to process
2021-02-16 19:01:26,023 - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/user/tezos-reward-distributor/src/pay/payment_consumer.py", line 117, in _consume_batch
    batch_payer.pay(payment_items, dry_run=self.dry_run)
  File "/user/tezos-reward-distributor/src/pay/batch_payer.py", line 174, in pay
    payment_address_balance = self.get_payment_address_balance()
  File "/user/tezos-reward-distributor/src/pay/batch_payer.py", line 513, in get_payment_address_balance
    return int(payment_address_balance)
ValueError: invalid literal for int() with base 10: ''
2021-02-16 19:01:29,935 - producer  - Calculation report is created at '/user/pymnt/reports/tz1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/calculations/322.csv'
2021-02-16 19:01:29,935 - producer  - Reward creation is done for cycle 322, created 104 rewards.
2021-02-16 19:01:35,124 - producer  - Unable to determine local node's bootstrap status. Continuing...
2021-02-16 19:01:35,369 - producer  - Checking for pending payments : checking 323 <= 328 - (5 + 1) - 0
2021-02-16 19:01:35,369 - producer  - No pending payments for cycle 323, current cycle is 328
2021-02-16 19:02:10,970 - producer_retry_fail - No failed payment files found under directory 

#here it is hanging... press ctrl-x

'/user/pymnt/reports/tz1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/payments/failed'

*******
Command for payout was:
python3 src/main.py -V on -C 321 -M 3 -P tzstats -A mainnet-tezos.giganode.io:443

**Comment by jdsika** [comment]
Can you check if #377 solves your issue, please?

**Comment by PolosatiiPsih** [comment]
Sorry, I didn't find any instructions/hints what to do there.

**Comment by jdsika** [comment]
Pull current master and it will show correct error messages now. Giganode now uses SSL ports. I think support will come this weekend for TRD #379
