### ISSUE TITLE
 Error in inject operation

### ISSUE THREAD

**Issue by SemElVik** [tezos-reward-distributor-organization/tezos-reward-distributor#407]
nothing works

previous branch
```2021-04-06 15:20:39,906 - consumer0 - Payment of batch 1 is complete, in 1 attempt(s)
2021-04-06 15:20:41,017 - consumer0 - Error in inject operation
2021-04-06 15:21:20,436 - consumer0 - Error in inject operation
2021-04-06 15:22:01,758 - consumer0 - Error in inject operation
2021-04-06 15:22:01,759 - consumer0 - Payment of batch 2 is complete, in 3 attempt(s)
2021-04-06 15:22:02,746 - consumer0 - Error in inject operation
2021-04-06 15:22:39,168 - consumer0 - Error in inject operation
2021-04-06 15:23:12,517 - consumer0 - Error in inject operation
2021-04-06 15:23:12,517 - consumer0 - Payment of batch 3 is complete, in 3 attempt(s)
2021-04-06 15:23:13,053 - consumer0 - Error in inject operation
2021-04-06 15:23:55,305 - consumer0 - Error in inject operation
2021-04-06 15:24:52,602 - consumer0 - Error in inject operation
2021-04-06 15:24:52,602 - consumer0 - Payment of batch 4 is complete, in 3 attempt(s)
2021-04-06 15:24:52,603 - consumer0 - Processing completed for 685 payment items, 485 failed.
2021-04-06 15:24:52,604 - consumer0 - Payment report is created at '/home/a/pymnt/reports/tz1.........../payments/failed/340.csv'
2021-04-06 15:24:52,633 - consumer0 - [Plugins] Not sending notification; no plugins enabled
2021-04-06 15:24:52,634 - consumer0 - [Plugins] Not sending notification; no plugins enabled
2021-04-06 15:24:52,635 - consumer0 - Sending anonymous statistics; See docs/statistics.rst for more information.
2021-04-06 15:24:53,723 - consumer0 - Exit signal received. Terminating...
2021-04-06 15:24:53,723 - consumer0 - Consumer returning ...```

after updating to a new branch 1cbf36f

~/tezos-reward-distributor$ python3 src/main.py -E http://127.0.0.1:6732 -C 340 -P tzkt -M 3 -O 10
Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    from util.process_life_cycle import ProcessLifeCycle
  File "/home/a/tezos-reward-distributor/src/util/process_life_cycle.py", line 13, in <module>
    from fsm.TransitionsFsmBuilder import TransitionsFsmBuilder
  File "/home/a/tezos-reward-distributor/src/fsm/TransitionsFsmBuilder.py", line 1, in <module>
    from transitions import Machine
ModuleNotFoundError: No module named 'transitions'

**Comment by vkresch** [comment]
@SemElVik please `pip install transitions`. Or use the requirements file via `pip install -r requirements.txt`.

**Comment by jdsika** [comment]
@vkresch this should be automatically checked. Normally TRD asks for the permission to install missing dependencies

**Comment by vkresch** [comment]
Ok I will look into it later and add it to the regression tests. This issue speaks for a trd pip package.

**Comment by SemElVik** [comment]
since my first packet flew away and was executed: and  3 packets were rejected due to an error, what do you now suggest me doing?
I cannot start TRD again with this loop as it will start over from the first batch.
how can I send failed 3 packets now (~ 600 transactions)

this is a question that does not require an answer.
