### ISSUE TITLE
The system failed to pay 5 batches: TypeError: unsupported operand type(s) for +=: 'int' and 'str'

### ISSUE THREAD

**Issue by TzBaker** [tezos-reward-distributor-organization/tezos-reward-distributor#414]
Today I have a new problem. The TRD failed to make all payments. I have a file with 200 accounts in the failed folder and the system can't process it with Error: unsupported operand type(s) for +=: 'int' and 'str'. also, after failed to pay TRD still sends a message that the payment successfully processed. Any advice on how can I fix it or work around it.

![image](https://user-images.githubusercontent.com/41934277/114216440-c39dd680-991b-11eb-99c6-6ba7630fdb2d.png)

2021-04-09 04:24:07,031 - producer  - Total rewards before processing is 1,419,573,757 mutez.
2021-04-09 04:24:07,084 - producer  - Total rewards after processing is 1,419,573,757 mutez.
2021-04-09 04:24:07,084 - producer  - Total amount to pay is 1,419,573,757 mutez
2021-04-09 04:24:07,084 - producer  - Difference between total rewards and total payment amount is 0 mutez. This is due to floating point arithmetic. (max allowed diff is 10)
2021-04-09 04:24:08,095 - consumer0 - Starting payments for cycle 341
2021-04-09 04:24:08,141 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegator
2021-04-09 04:24:08,141 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2021-04-09 04:24:08,142 - consumer0 - Payment amount cutoff is 0.000575 XTZ
2021-04-09 04:24:08,142 - consumer0 - 1597 payment items to process
2021-04-09 04:24:08,162 - consumer0 - Total amount to pay out is 1,419,506,695 mutez.
2021-04-09 04:24:08,163 - consumer0 - Current balance in payout address is 2,500,243,491 mutez.
2021-04-09 04:24:08,163 - consumer0 - 917 payments will be done in 5 batches
2021-04-09 04:24:08,166 - consumer0 - The payout address will soon run out of funds. The current balance, 2,500,243,491 mutez, might not be sufficient for the next cycle
2021-04-09 04:24:09,085 - consumer0 - [TelegramPlugin] Admin Notification 'WARNING Payouts - Low Payment Address Funds' sent
2021-04-09 04:24:12,312 - producer  - Calculation report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/calculations/341.csv'
2021-04-09 04:24:12,312 - producer  - Reward creation is done for cycle 341, created 1601 rewards.
2021-04-09 04:24:12,615 - consumer0 - Operation hash is onjyrcYFjwCkngk8T3BAk3EXDezFgV7pzxannLwkLjup1DB4prH
2021-04-09 04:24:12,615 - consumer0 - Waiting for operation onjyrcYFjwCkngk8T3BAk3EXDezFgV7pzxannLwkLjup1DB4prH to be included...
2021-04-09 04:24:17,381 - producer  - Checking for pending payments : checking 342 <= 347 - (5 + 1) - 0
2021-04-09 04:24:17,382 - producer  - No pending payments for cycle 342, current cycle is 347
2021-04-09 04:25:12,652 - consumer0 - Operation onjyrcYFjwCkngk8T3BAk3EXDezFgV7pzxannLwkLjup1DB4prH is included
2021-04-09 04:25:12,654 - consumer0 - Payment of batch 1 is complete, in 1 attempt(s)
2021-04-09 04:25:14,896 - consumer0 - Operation hash is oowDnDHkpYjd6QYuVNhCDqrZzbFE5pEMLPRSGqjdPSR9121Gmr7
2021-04-09 04:25:14,897 - consumer0 - Waiting for operation oowDnDHkpYjd6QYuVNhCDqrZzbFE5pEMLPRSGqjdPSR9121Gmr7 to be included...
2021-04-09 04:26:14,916 - consumer0 - Operation oowDnDHkpYjd6QYuVNhCDqrZzbFE5pEMLPRSGqjdPSR9121Gmr7 is included
2021-04-09 04:26:14,919 - consumer0 - Payment of batch 2 is complete, in 1 attempt(s)
2021-04-09 04:26:15,213 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 04:26:59,421 - consumer0 - batch payment attempt 2/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 04:27:51,624 - consumer0 - batch payment attempt 3/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 04:27:51,625 - consumer0 - Payment of batch 3 is complete, in 3 attempt(s)
2021-04-09 04:27:53,852 - consumer0 - Operation hash is oo8wc7keLD7MToyuiFk3tNt6Ccx69wD99p4BrEWrawUgYfCHjqX
2021-04-09 04:27:53,852 - consumer0 - Waiting for operation oo8wc7keLD7MToyuiFk3tNt6Ccx69wD99p4BrEWrawUgYfCHjqX to be included...
2021-04-09 04:28:02,894 - producer_retry_fail - No failed payment files found under directory '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed'
2021-04-09 04:28:53,933 - consumer0 - Operation oo8wc7keLD7MToyuiFk3tNt6Ccx69wD99p4BrEWrawUgYfCHjqX is included
2021-04-09 04:28:53,935 - consumer0 - Payment of batch 4 is complete, in 1 attempt(s)
2021-04-09 04:28:55,308 - consumer0 - Operation hash is onvMrvme71nL3X4yhUmb3NUaJDmtVzCAzfLUwms4D4htPmJLa8b
2021-04-09 04:28:55,308 - consumer0 - Waiting for operation onvMrvme71nL3X4yhUmb3NUaJDmtVzCAzfLUwms4D4htPmJLa8b to be included...
2021-04-09 04:30:55,392 - consumer0 - Operation onvMrvme71nL3X4yhUmb3NUaJDmtVzCAzfLUwms4D4htPmJLa8b is included
2021-04-09 04:30:55,394 - consumer0 - Payment of batch 5 is complete, in 1 attempt(s)
2021-04-09 04:30:55,395 - consumer0 - Processing completed for 917 payment items, 200 failed.
2021-04-09 04:30:55,401 - consumer0 - Payment report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv'
2021-04-09 04:30:56,352 - consumer0 - [TelegramPlugin] Public Notification '&#x2728; Reward for ...' sent
2021-04-09 04:30:56,589 - consumer0 - [TwitterPlugin] Payout Notification 'Reward for cycle 341 complete! We had 917 delegators in the cycle and paid out 1419.51 XTZ in rewards. #baketz #rewards #tezos
' sent
2021-04-09 04:30:57,292 - consumer0 - [TelegramPlugin] Admin Notification 'Reward Payouts for Cycle 341 attempted, 200 failed' sent
2021-04-09 04:30:57,302 - consumer0 - Sending anonymous statistics; See docs/statistics.rst for more information.
2021-04-09 05:28:02,896 - producer_retry_fail - Working on failed payment file /home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv
2021-04-09 05:28:02,926 - producer_retry_fail - Summary 717 paid, 0 done, 0 injected, 200 fail
2021-04-09 05:31:51,770 - consumer0 - Starting payments for cycle 341
2021-04-09 05:31:51,774 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegator
2021-04-09 05:31:51,774 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2021-04-09 05:31:51,774 - consumer0 - Payment amount cutoff is 0.000575 XTZ
2021-04-09 05:31:51,775 - consumer0 - 200 payment items to process
2021-04-09 05:31:51,784 - consumer0 - Total amount to pay out is 5,752,209 mutez.
2021-04-09 05:31:51,784 - consumer0 - Current balance in payout address is 1,086,894,383 mutez.
2021-04-09 05:31:51,784 - consumer0 - 200 payments will be done in 1 batches
2021-04-09 05:31:51,784 - consumer0 - The payout account balance is expected to last for the next 187 cycle(s)
2021-04-09 05:31:51,954 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 05:32:52,115 - consumer0 - batch payment attempt 2/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 05:33:35,275 - consumer0 - batch payment attempt 3/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 05:33:35,277 - consumer0 - Payment of batch 1 is complete, in 3 attempt(s)
2021-04-09 05:33:35,278 - consumer0 - Processing completed for 200 payment items, 200 failed.
2021-04-09 05:33:35,280 - consumer0 - Payment report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv'
2021-04-09 05:33:36,217 - consumer0 - [TelegramPlugin] Public Notification '&#x2728; Reward for ...' sent
2021-04-09 05:33:36,446 - consumer0 - [TwitterPlugin] Payout Notification 'Reward for cycle 341 complete! We had 200 delegators in the cycle and paid out 5.75 XTZ in rewards. #baketz #rewards #tezos
' sent
2021-04-09 05:33:37,171 - consumer0 - [TelegramPlugin] Admin Notification 'Reward Payouts for Cycle 341 attempted, 200 failed' sent
2021-04-09 05:33:37,173 - consumer0 - Sending anonymous statistics; See docs/statistics.rst for more information.
2021-04-09 06:31:50,771 - producer_retry_fail - Working on failed payment file /home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv
2021-04-09 06:31:50,779 - producer_retry_fail - Summary 0 paid, 0 done, 0 injected, 200 fail
2021-04-09 06:35:42,521 - consumer0 - Starting payments for cycle 341
2021-04-09 06:35:42,525 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegator
2021-04-09 06:35:42,525 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2021-04-09 06:35:42,526 - consumer0 - Payment amount cutoff is 0.000575 XTZ
2021-04-09 06:35:42,526 - consumer0 - 200 payment items to process
2021-04-09 06:35:42,536 - consumer0 - Total amount to pay out is 5,752,209 mutez.
2021-04-09 06:35:42,536 - consumer0 - Current balance in payout address is 1,086,894,383 mutez.
2021-04-09 06:35:42,537 - consumer0 - 200 payments will be done in 1 batches
2021-04-09 06:35:42,537 - consumer0 - The payout account balance is expected to last for the next 187 cycle(s)
2021-04-09 06:35:42,725 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 06:36:16,896 - consumer0 - batch payment attempt 2/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 06:36:49,072 - consumer0 - batch payment attempt 3/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 06:36:49,074 - consumer0 - Payment of batch 1 is complete, in 3 attempt(s)
2021-04-09 06:36:49,075 - consumer0 - Processing completed for 200 payment items, 200 failed.
2021-04-09 06:36:49,077 - consumer0 - Payment report is created at '/home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv'
2021-04-09 06:36:49,996 - consumer0 - [TelegramPlugin] Public Notification '&#x2728; Reward for ...' sent
2021-04-09 06:36:50,159 - consumer0 - [Plugins] [Twitter] Unknown Error: [{'code': 187, 'message': 'Status is a duplicate.'}]
2021-04-09 06:36:50,875 - consumer0 - [TelegramPlugin] Admin Notification 'Reward Payouts for Cycle 341 attempted, 200 failed' sent
2021-04-09 06:36:50,876 - consumer0 - Sending anonymous statistics; See docs/statistics.rst for more information.
2021-04-09 07:35:41,538 - producer_retry_fail - Working on failed payment file /home/tzpc-2/pymnt/reports/tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3/payments/failed/341.csv
2021-04-09 07:35:41,557 - producer_retry_fail - Summary 0 paid, 0 done, 0 injected, 200 fail
2021-04-09 07:39:53,296 - consumer0 - Starting payments for cycle 341
2021-04-09 07:39:53,300 - consumer0 - Transfer fee is 0.000574 XTZ and is paid by Delegator
2021-04-09 07:39:53,300 - consumer0 - Reactivation fee is 0.257000 XTZ and is paid by Delegator
2021-04-09 07:39:53,301 - consumer0 - Payment amount cutoff is 0.000575 XTZ
2021-04-09 07:39:53,301 - consumer0 - 200 payment items to process
2021-04-09 07:39:53,313 - consumer0 - Total amount to pay out is 5,752,209 mutez.
2021-04-09 07:39:53,313 - consumer0 - Current balance in payout address is 1,086,894,383 mutez.
2021-04-09 07:39:53,314 - consumer0 - 200 payments will be done in 1 batches
2021-04-09 07:39:53,314 - consumer0 - The payout account balance is expected to last for the next 187 cycle(s)
2021-04-09 07:39:53,507 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 07:40:53,770 - consumer0 - batch payment attempt 2/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-04-09 07:41:32,018 - consumer0 - batch payment attempt 3/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 243, in pay_single_batch
	status, operation_hash = self.attempt_single_batch(payment_items, op_counter, dry_run=dry_run)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 359, in attempt_single_batch
	simulation_status, simulation_results = self.simulate_single_operation(payment_item, pymnt_amnt, branch, chain_id)
  File "/home/tzpc-2/tezos-reward-distributor/src/pay/batch_payer.py", line 322, in simulate_single_operation
	storage += internal_op['result']['paid_storage_size_diff']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

**Comment by vkresch** [comment]
@TzBaker try updating trd to the latest master if possible. A month ago trd received an update from:
```python
storage += internal_op['result']['paid_storage_size_diff']
```
to
```python
storage += int(internal_op['result']['paid_storage_size_diff'])
```
making a casting from str -> int for the paid_storage_size_diff thus avoid the issue you got.

**Comment by TzBaker** [comment]
@vkresch It works. Thank you!
