### ISSUE TITLE
ERROR - [get_d_d_b] Unexpected error: int() argument must be a string, a bytes-like object or a number, not 'dict'

### ISSUE THREAD

**Issue by TzBaker** [tezos-reward-distributor-organization/tezos-reward-distributor#483]
**Describe the bug**
I downloaded the new version today and try to pay for Cycle 382 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Terminal
2. Run command: python3 src/main.py -C 382 -M 3
3. Multi errors (see log below)

**Environment**
 - Source Code Build
 - Chain mainnet
 - Ubuntu 20.04.2 LTS

**Additional context**
LOG:
2021-08-11 09:42:12,341 - MainThread - INFO - Initial cycle set to 382
2021-08-11 09:42:12,347 - MainThread - INFO - Application is READY!
2021-08-11 09:42:12,348 - MainThread - INFO - --------------------------------------------
2021-08-11 09:42:17,695 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:42:17,695 - producer  - INFO - Payment cycle is 382
2021-08-11 09:42:17,696 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:44:19,785 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:44:19,786 - producer  - ERROR - [try_to_pay] API provider error [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:44:19,798 - producer  - ERROR - RPC error at payment producer loop: '[do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s', will try again.
2021-08-11 09:44:25,074 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:44:25,074 - producer  - INFO - Payment cycle is 382
2021-08-11 09:44:25,074 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:46:28,432 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:46:28,432 - producer  - ERROR - [try_to_pay] API provider error [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:46:28,434 - producer  - ERROR - RPC error at payment producer loop: '[do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s', will try again.
2021-08-11 09:46:33,605 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:46:33,606 - producer  - INFO - Payment cycle is 382
2021-08-11 09:46:33,606 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:46:47,933 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544192/context/contracts/tz1gzy9kebB3YKx2nHbK3fJavBYR6rNSwJg7/balance' timed out after 5s
2021-08-11 09:46:49,601 - producer  - ERROR - [get_d_d_b] Unexpected error: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 409, in __get_delegators_and_delgators_balances
    d_info["staking_balance"] = int(staking_balance_response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:46:49,602 - producer  - ERROR - [try_to_pay] Generic exception int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:46:49,603 - producer  - ERROR - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict', will try again.
2021-08-11 09:46:54,811 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:46:54,812 - producer  - INFO - Payment cycle is 382
2021-08-11 09:46:54,812 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:47:06,665 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/contracts/tz1gzy9kebB3YKx2nHbK3fJavBYR6rNSwJg7/balance' timed out after 5s
2021-08-11 09:47:06,666 - producer  - WARNING - Fetching delegator tz1gzy9kebB3YKx2nHbK3fJavBYR6rNSwJg7 current balance failed, will retry: [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/contracts/tz1gzy9kebB3YKx2nHbK3fJavBYR6rNSwJg7/balance' timed out after 5s
2021-08-11 09:47:16,933 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/contracts/tz1iXqXtMKWgGTTyQaMJtRLicS77N5jUhBBz/balance' timed out after 5s
2021-08-11 09:47:16,934 - producer  - WARNING - Fetching delegator tz1iXqXtMKWgGTTyQaMJtRLicS77N5jUhBBz current balance failed, will retry: [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/head/context/contracts/tz1iXqXtMKWgGTTyQaMJtRLicS77N5jUhBBz/balance' timed out after 5s
2021-08-11 09:47:25,557 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544192/context/contracts/tz1Q5pLJqsrH67MQd2YHcsFLBqYUPYEd9rkR/balance' timed out after 5s
2021-08-11 09:47:31,904 - producer  - ERROR - [get_d_d_b] Unexpected error: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 409, in __get_delegators_and_delgators_balances
    d_info["staking_balance"] = int(staking_balance_response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:47:31,904 - producer  - ERROR - [try_to_pay] Generic exception int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:47:31,905 - producer  - ERROR - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict', will try again.
2021-08-11 09:47:37,084 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:47:37,085 - producer  - INFO - Payment cycle is 382
2021-08-11 09:47:37,085 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:47:39,168 - producer  - ERROR - [try_to_pay] Generic exception can only concatenate list (not "int") to list
2021-08-11 09:47:39,169 - producer  - ERROR - Unknown error in payment producer loop: can only concatenate list (not "int") to list, will try again.
2021-08-11 09:47:44,417 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:47:44,417 - producer  - INFO - Payment cycle is 382
2021-08-11 09:47:44,418 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:47:47,171 - producer  - ERROR - [get_d_d_b] Unexpected error: string indices must be integers
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 374, in __get_delegators_and_delgators_balances
    delegate_staking_balance = int(response["staking_balance"])
TypeError: string indices must be integers
2021-08-11 09:47:47,171 - producer  - ERROR - [try_to_pay] Generic exception string indices must be integers
2021-08-11 09:47:47,172 - producer  - ERROR - Unknown error in payment producer loop: string indices must be integers, will try again.
2021-08-11 09:47:52,490 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:47:52,490 - producer  - INFO - Payment cycle is 382
2021-08-11 09:47:52,490 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:48:21,247 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544192/context/contracts/tz1d1pqpbhoDJEnUC9S5Jvp727GAiZSumZEC/balance' timed out after 5s
2021-08-11 09:48:29,735 - producer  - ERROR - [get_d_d_b] Unexpected error: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 409, in __get_delegators_and_delgators_balances
    d_info["staking_balance"] = int(staking_balance_response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:48:29,736 - producer  - ERROR - [try_to_pay] Generic exception int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:48:29,737 - producer  - ERROR - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict', will try again.
2021-08-11 09:48:36,592 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:48:36,592 - producer  - INFO - Payment cycle is 382
2021-08-11 09:48:36,592 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:50:39,305 - producer  - ERROR - [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:50:39,306 - producer  - ERROR - [try_to_pay] API provider error [do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s
2021-08-11 09:50:39,308 - producer  - ERROR - RPC error at payment producer loop: '[do_rpc_request] Requesting URL 'https://mainnet-tezos.giganode.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' timed out after 120s', will try again.
2021-08-11 09:50:44,488 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:50:44,488 - producer  - INFO - Payment cycle is 382
2021-08-11 09:50:44,489 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 09:50:51,629 - producer  - ERROR - [get_d_d_b] Unexpected error: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/home/tzpc-2/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 409, in __get_delegators_and_delgators_balances
    d_info["staking_balance"] = int(staking_balance_response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:50:51,630 - producer  - ERROR - [try_to_pay] Generic exception int() argument must be a string, a bytes-like object or a number, not 'dict'
2021-08-11 09:50:51,630 - producer  - ERROR - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict', will try again.
2021-08-11 09:50:56,874 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 09:50:56,874 - producer  - INFO - Payment cycle is 382
2021-08-11 09:50:56,875 - producer  - INFO - Using actual rewards for payouts calculations

**Comment by denver-s** [comment]
Can you try with `python3 src/main.py -C 382 -M 3 -Ap https://mainnet.smartpy.io` ?

**Comment by TzBaker** [comment]
@denver-s I tried and this is the Log:
2021-08-11 10:26:45,291 - MainThread - INFO - Application is READY!
2021-08-11 10:26:45,291 - MainThread - INFO - --------------------------------------------
2021-08-11 10:26:50,526 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:26:50,527 - producer  - INFO - Payment cycle is 382
2021-08-11 10:26:50,527 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:26:54,063 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:26:54,066 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:26:59,230 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:26:59,230 - producer  - INFO - Payment cycle is 382
2021-08-11 10:26:59,230 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:00,734 - producer  - ERROR - [try_to_pay] Generic exception Expecting value: line 1 column 1 (char 0)
2021-08-11 10:27:00,738 - producer  - ERROR - Unknown error in payment producer loop: Expecting value: line 1 column 1 (char 0), will try again.
2021-08-11 10:27:05,912 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:05,912 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:05,913 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:07,003 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:27:07,005 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:27:12,216 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:12,217 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:12,217 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:13,339 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:27:13,341 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:27:18,613 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:18,613 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:18,613 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:22,577 - producer  - ERROR - [try_to_pay] Generic exception Expecting value: line 1 column 1 (char 0)
2021-08-11 10:27:22,578 - producer  - ERROR - Unknown error in payment producer loop: Expecting value: line 1 column 1 (char 0), will try again.
2021-08-11 10:27:27,829 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:27,829 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:27,829 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:29,029 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:27:29,030 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:27:34,308 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:34,309 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:34,309 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:35,842 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:27:35,843 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:27:41,179 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:41,179 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:41,179 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:43,901 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:27:43,902 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:27:49,207 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:49,207 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:49,207 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:51,035 - producer  - ERROR - [try_to_pay] Generic exception Expecting value: line 1 column 1 (char 0)
2021-08-11 10:27:51,036 - producer  - ERROR - Unknown error in payment producer loop: Expecting value: line 1 column 1 (char 0), will try again.
2021-08-11 10:27:56,312 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:27:56,312 - producer  - INFO - Payment cycle is 382
2021-08-11 10:27:56,312 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:27:57,758 - producer  - ERROR - [try_to_pay] Generic exception Expecting value: line 1 column 1 (char 0)
2021-08-11 10:27:57,759 - producer  - ERROR - Unknown error in payment producer loop: Expecting value: line 1 column 1 (char 0), will try again.
2021-08-11 10:28:03,293 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:28:03,293 - producer  - INFO - Payment cycle is 382
2021-08-11 10:28:03,293 - producer  - INFO - Using actual rewards for payouts calculations
2021-08-11 10:28:04,544 - producer  - ERROR - [try_to_pay] API provider error RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?
2021-08-11 10:28:04,545 - producer  - ERROR - RPC error at payment producer loop: 'RPC URL 'https://mainnet.smartpy.io/chains/main/blocks/1544193/context/raw/json/cycle/382/roll_snapshot' not found. Is this node in archive mode?', will try again.
2021-08-11 10:28:09,710 - producer  - INFO - Checking for pending payments: checking 382 <= 389 - (5 + 1) - 0
2021-08-11 10:28:09,711 - producer  - INFO - Payment cycle is 382
2021-08-11 10:28:09,711 - producer  - INFO - Using actual rewards for payouts calculations

**Comment by denver-s** [comment]
Ouch, I didn't know that Smartpy is not reliable on these RPCs. Maybe `https://rpc.tzkt.io:443/mainnet/` or `https://mainnet-node.madfish.solutions` ?

**Comment by TzBaker** [comment]
@denver-s Looks like working! Thank you! Should I use for recursive payment command like: python3 src/main.py -Ap https://rpc.tzkt.io:443/mainnet/ ?

**Comment by denver-s** [comment]
@TzBaker actually you might want to use `python3 src/main.py -P tzkt -Ap https://rpc.tzkt.io:443/mainnet/` and avoid the heavy RPCs call.

**Comment by TzBaker** [comment]
@denver-s Thank you Thank you!!
