### ISSUE TITLE
Estimated payout calculation fails in "rpc" provider mode

### ISSUE THREAD

**Issue by teddyknox** [tezos-reward-distributor-organization/tezos-reward-distributor#489]
When running TRD like so
```
python /app/src/main.py \
    -D \
    -d \
    -f /app/config \
    -r /root \
    -C 380 \
    -R -5 \
    -P tzkt \
    -A https://rpc.tzkt.io:443/mainnet
```

We encounter failures likes so
```
2021-08-12 21:45:26,145 - producer  - DEBUG - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/app/src/pay/payment_producer.py", line 192, in run
    result = self.try_to_pay(pymnt_cycle, self.rewards_type)
  File "/app/src/pay/payment_producer.py", line 299, in try_to_pay
    raise e from e
  File "/app/src/pay/payment_producer.py", line 267, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle, rewards_type)
  File "/app/src/rpc/rpc_reward_api.py", line 141, in get_rewards_for_cycle_map
    raise e from e
  File "/app/src/rpc/rpc_reward_api.py", line 57, in get_rewards_for_cycle_map
    "delegators"] = self.__get_delegators_and_delgators_balances(cycle, current_level)
  File "/app/src/rpc/rpc_reward_api.py", line 415, in __get_delegators_and_delgators_balances
    raise e from e
  File "/app/src/rpc/rpc_reward_api.py", line 402, in __get_delegators_and_delgators_balances
    d_info["current_balance"] = self.__get_current_balance_of_delegator(delegator)
  File "/app/src/rpc/rpc_reward_api.py", line 443, in __get_current_balance_of_delegator
    return int(current_balance_response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

This causes TRD to fail to calculate payments for this cycle. I'm running this within a docker container.

**Comment by denver-s** [comment]
Can you try again with `-V on`? It would be useful to get the actual RPC request and its response

**Comment by denver-s** [comment]
There’s a typo or did you run with `-P tzkt`?

**Comment by denver-s** [comment]
@teddyknox lines don't seem to match to the current code in master. Can you please update your repository?

**Comment by jdsika** [comment]
I will close this issue until a -V verbose log while using the current master branch is submitted for further investigation
