### ISSUE TITLE
signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}

### ISSUE THREAD

**Issue by songproducer** [tezos-reward-distributor-organization/tezos-reward-distributor#589]
```
2022-04-08 01:20:14,729 - consumer0 - ERROR - Batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/Users/leotreasure/tezos-reward-distributor/src/pay/batch_payer.py", line 465, in pay_single_batch
    status, operation_hash, error_message = self.attempt_single_batch(
  File "/Users/leotreasure/tezos-reward-distributor/src/pay/batch_payer.py", line 932, in attempt_single_batch
    signed_bytes = self.clnt_mngr.sign(bytes, self.manager)
  File "/Users/leotreasure/tezos-reward-distributor/src/cli/client_manager.py", line 114, in sign
    raise ClientException(
exception.client.ClientException: Error at signing. Make sure tezos-signer is up and running 'tezos-signer launch http signer': '[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
2022-04-08 01:20:14,730 - consumer0 - INFO - Payment of batch 3 succeeded in 1 attempt(s)
```
Obviously it did not succeed. I tried to reduce the MAX_TX_PER_BLOCK_TZ and MAX_TX_PER_BLOCK_KT values which showed a KT address on the ledger but everything else was still failed so I rejected the transaction.

**Comment by jdsika** [comment]
Die you got pull? I think I fixed that already some days ago? Sunday?

**Comment by songproducer** [comment]
Yes
On branch ithaca2
Your branch is up to date with 'origin/ithaca2'.

**Comment by songproducer** [comment]
Is there any thing I can try to make the payouts work?

**Comment by jdsika** [comment]
The first thing is to explain your setup. What payout address are you using? Which curve. As much as possible. We have to understand why it works for everyone but you. Also please do git log and tell me your commit hash

**Comment by songproducer** [comment]
Payout address is tz1MdSsDBG8k8q1pxZrdpSC2Aw49ukFs8ACy which is a custom derivation path on Ledger Nano X
Curve is ED25519
MacOS Monterey 12.3.1 (21E258)
Python 3.8.11
cat .git/refs/heads/ithaca2
bd7c53d14a7188f2ec9a0bdee0f229948fa4474d

https://ghostbin.com/MhoxN

**Comment by jdsika** [comment]
Wait, reading the error message again it says that the signer is not working properly. It has apparently nothing to do with the batch size etc?

**Comment by jdsika** [comment]
what ledger firmware and wallet version?

**Comment by songproducer** [comment]
> Wait, reading the error message again it says that the signer is not working properly. It has apparently nothing to do with the batch size etc?

That may be from a few times I tried before plugging in the Ledger. The msg-chunk-too-big error definitely shows when ledger is plugged in.

**Comment by songproducer** [comment]
> what ledger firmware and wallet version?

Ledger Tezos Wallet 2.2.15
Ledger Live v2.40.2

**Comment by jdsika** [comment]
Quick fix:
Set up a dedicated hot wallet as payout Wallet. Put it in the config. Import into the signer. Fund it with Tez enough for the cycle you intend to pay and try again.

Also:
Create an issue in the ledger wallet and link it here. I somehow suspect an issue there.

**Comment by songproducer** [comment]
Thanks, will do!

**Comment by gregthebaker** [comment]
I am trying to send payments for cycle 465  and I am encountering the following error. The signer is up and running as normal and I am on the ithica2 branch of TRD. What's odd is that it doesnt mark the payment as failed either.
`2022-04-12 08:56:18,353 - consumer0 - ERROR - Error, request ->POST http://127.0.0.1:6732/keys/<baker_address><-, params ->"<_params>"<-,
---
Error, response ->[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
<-
2022-04-12 08:56:18,353 - consumer0 - ERROR - Batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 465, in pay_single_batch
    status, operation_hash, error_message = self.attempt_single_batch(
  File "/home/user/tezos-reward-distributor/src/pay/batch_payer.py", line 932, in attempt_single_batch
    signed_bytes = self.clnt_mngr.sign(bytes, self.manager)
  File "/home/user/tezos-reward-distributor/src/cli/client_manager.py", line 114, in sign
    raise ClientException(
exception.client.ClientException: Error at signing. Make sure tezos-signer is up and running 'tezos-signer launch http signer': '[{"kind":"permanent","id":"signer.ledger.msg-chunk-too-big","msg":"sign-with-hash"}]
'
2022-04-12 08:56:18,363 - consumer0 - INFO - Payment of batch 1 succeeded in 1 attempt(s)
2022-04-12 08:56:18,364 - consumer0 - INFO - Total amount payed out is 0 mutez in 1 attempts and 1 batches.
2022-04-12 08:56:18,364 - consumer0 - INFO - Processing completed for 7 payment items.
2022-04-12 08:56:18,364 - consumer0 - INFO - Payment report is created at '/home/user/pymnt/reports/<baker_address>/payments/done/465.csv'
2022-04-12 08:56:18,369 - consumer0 - INFO - Calculation report is created at '/home/user/pymnt/reports/<baker_address>/calculations/465.csv'
2022-04-12 08:56:18,369 - consumer0 - INFO - Simulated transaction_fees added to calculations file.
2022-04-12 08:56:18,369 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
2022-04-12 08:56:18,369 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
2022-04-12 08:56:18,371 - consumer0 - INFO - Sending anonymous statistics; See docs/statistics.rst for more information.
2022-04-12 08:56:21,624 - producer  - INFO - Reward creation is done for cycle 465, created 17 rewards.
2022-04-12 08:56:27,058 - producer  - INFO - Checking for pending payments: checking 466 <= 471 - (5 + 1) - 0
2022-04-12 08:56:27,058 - producer  - INFO - No pending payments for cycle 466, current cycle is 471
2022-04-12 08:56:27,058 - producer  - INFO - Run mode PENDING satisfied. Terminating...
2022-04-12 08:56:27,059 - producer  - INFO - Sending KeyboardInterrupt signal.
2022-04-12 08:56:27,059 - consumer0 - WARNING - Exit signal received. Terminating...
2022-04-12 08:56:27,934 - MainThread - INFO - Interrupted.
2022-04-12 08:56:27,934 - MainThread - INFO - TRD is shutting down...
2022-04-12 08:56:27,934 - MainThread - INFO - --------------------------------------------------------
2022-04-12 08:56:27,935 - MainThread - INFO - Sensitive operations are in progress!
2022-04-12 08:56:27,935 - MainThread - INFO - Please wait while the application is being shut down!
2022-04-12 08:56:27,935 - MainThread - INFO - --------------------------------------------------------
2022-04-12 08:56:27,935 - MainThread - INFO - Lock file removed!`

`address,type,amount,hash,paid,description
tz1[snip],D,210,None,done,Payment amount < ZERO_THRESHOLD.
tz1[snip],D,1237106,None,undefined,
tz1[snip],D,908301,None,undefined,
tz1[snip],D,171825,None,undefined,
tz1[snip],D,31126,None,undefined,
tz1[snip],D,10685,None,undefined,
tz1[snip],M,2864379,None,undefined,`

**Comment by gregthebaker** [comment]
Upgrading the ledger tezos wallet app to version 2.3.2 fixed the issue

**Comment by Arbitriom** [comment]
> Upgrading the ledger tezos wallet app to version 2.3.2 fixed the issue

how did you upgrade your Nano S to 2.3.2 ? 
Nano S firmware : 2.1.0
Tezos wallet : 2.2.15 and nothing available to update :/

**Comment by gregthebaker** [comment]
This is how you can upgrade your tezos-wallet app to 2.3.2
![image](https://user-images.githubusercontent.com/94792725/164711656-f9b6a6b0-785d-4595-b3ec-7f519d49732f.png)

**Comment by rvermootenct** [comment]
Closing stale issues, please reopen if still an issue for you.
