### ISSUE TITLE
Error when using on new v19.0 node version

### ISSUE THREAD

**Issue by sargatxet** [tezos-reward-distributor-organization/tezos-reward-distributor#696]
Now, when trying to calculate rewards for 702 cicle I get this

`
2024-02-09 15:47:14,724 - producer  - DEBUG - Cycle 702, blocks per cycle 16384, last block of cycle 6750208
2024-02-09 15:47:14,830 - producer  - ERROR - [try_to_pay] Generic exception int() argument must be a string, a bytes-like object or a number, not 'dict'
2024-02-09 15:47:14,831 - producer  - DEBUG - Unknown error in payment producer loop: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/pay/payment_producer.py", line 304, in run
    result = self.try_to_pay(
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/pay/payment_producer.py", line 630, in try_to_pay
    raise e from e
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/pay/payment_producer.py", line 562, in try_to_pay
    reward_logs, total_amount = self.compute_rewards(
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/pay/payment_producer.py", line 412, in compute_rewards
    reward_model = self.reward_api.get_rewards_for_cycle_map(
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/rpc/rpc_reward_api.py", line 256, in get_rewards_for_cycle_map
    raise e from e
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/rpc/rpc_reward_api.py", line 123, in get_rewards_for_cycle_map
    potential_endorsement_rewards = self.get_potential_endorsement_rewards(
  File "/home/tezosbaker/.tezos-reward-distributor/dist/src/rpc/rpc_reward_api.py", line 336, in get_potential_endorsement_rewards
    total_active_stake = int(self.do_rpc_request(total_active_stake_rpc))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'`

Any suggestion?

**Comment by jdsika** [comment]
What is the command you are using?

**Comment by sargatxet** [comment]
`/usr/bin/bash -c 'cd /home/tezosbaker/.tezos-reward-distributor/dist/ && source ../.venv/bin/activate && python3 src/main.py -O 1011 -E http://localhost:6732 -V on -A http://localhost:8732 -P rpc -s'`

**Comment by jdsika** [comment]
Alright, I suggest you use tzkt backend for now as provider until someone has a look at it.
Same with v19.1 I guess?

**Comment by sargatxet** [comment]
Thanks
